
        const tryRequire = (path) => {
        	try {
        	const image = require(`${path}`);
        	return image
        	} catch (err) {
        	return false
        	}
        };

        export default {
        
	questionMark: require('./questionMark.png'),
	List_Vector: tryRequire('./List_Vector.png') || require('./questionMark.png'),
	MagnifyingGlass_Vector: tryRequire('./MagnifyingGlass_Vector.png') || require('./questionMark.png'),
	User_Vector: tryRequire('./User_Vector.png') || require('./questionMark.png'),
	ShoppingCart_Vector: tryRequire('./ShoppingCart_Vector.png') || require('./questionMark.png'),
	Property1Web_KickoffKits: tryRequire('./Property1Web_KickoffKits.png') || require('./questionMark.png'),
	FunnelSimple_Vector: tryRequire('./FunnelSimple_Vector.png') || require('./questionMark.png'),
	XCircle_Vector: tryRequire('./XCircle_Vector.png') || require('./questionMark.png'),
	ShoppingCart_1_Vector: tryRequire('./ShoppingCart_1_Vector.png') || require('./questionMark.png'),
	Heart_Vector: tryRequire('./Heart_Vector.png') || require('./questionMark.png'),
	Star_Vector: tryRequire('./Star_Vector.png') || require('./questionMark.png'),
	Property1Default_2_Frame21: tryRequire('./Property1Default_2_Frame21.png') || require('./questionMark.png'),
	CaretDoubleLeft_Vector: tryRequire('./CaretDoubleLeft_Vector.png') || require('./questionMark.png'),
	CaretLeft_Vector: tryRequire('./CaretLeft_Vector.png') || require('./questionMark.png'),
	CaretRight_Vector: tryRequire('./CaretRight_Vector.png') || require('./questionMark.png'),
	CaretDoubleRight_Vector: tryRequire('./CaretDoubleRight_Vector.png') || require('./questionMark.png'),
	EnvelopeSimple_Vector: tryRequire('./EnvelopeSimple_Vector.png') || require('./questionMark.png'),
	ArrowRight_Vector: tryRequire('./ArrowRight_Vector.png') || require('./questionMark.png'),
	SnapchatLogo_Vector: tryRequire('./SnapchatLogo_Vector.png') || require('./questionMark.png'),
	InstagramLogo_Vector: tryRequire('./InstagramLogo_Vector.png') || require('./questionMark.png'),
	XLogo_Vector: tryRequire('./XLogo_Vector.png') || require('./questionMark.png'),
	FacebookLogo_Vector: tryRequire('./FacebookLogo_Vector.png') || require('./questionMark.png'),
	TelegramLogo_Vector: tryRequire('./TelegramLogo_Vector.png') || require('./questionMark.png'),
	X_Vector: tryRequire('./X_Vector.png') || require('./questionMark.png'),
	CaretDown_Vector: tryRequire('./CaretDown_Vector.png') || require('./questionMark.png'),
	SideBarCOntainer_KickoffKits: tryRequire('./SideBarCOntainer_KickoffKits.png') || require('./questionMark.png'),
	Trash_Vector: tryRequire('./Trash_Vector.png') || require('./questionMark.png'),
	Property1Mobile_KickoffKits: tryRequire('./Property1Mobile_KickoffKits.png') || require('./questionMark.png'),
	CaretDown_1_Vector: tryRequire('./CaretDown_1_Vector.png') || require('./questionMark.png'),
	SortDesc_Vector6932: tryRequire('./SortDesc_Vector6932.png') || require('./questionMark.png'),
	SOrtAscend_Vector6931: tryRequire('./SOrtAscend_Vector6931.png') || require('./questionMark.png'),
	Ticket_Vector: tryRequire('./Ticket_Vector.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector: tryRequire('./PaymentConfirmationModalMobileView_Vector.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector: tryRequire('./PaymentConfirmationModalDesktop_Vector.png') || require('./questionMark.png'),
	Property1Mobile_1_KickoffKits: tryRequire('./Property1Mobile_1_KickoffKits.png') || require('./questionMark.png'),
	MinusCircle_Vector: tryRequire('./MinusCircle_Vector.png') || require('./questionMark.png'),
	PlusCircle_Vector: tryRequire('./PlusCircle_Vector.png') || require('./questionMark.png'),
	Heart_1_Vector: tryRequire('./Heart_1_Vector.png') || require('./questionMark.png'),
	Property1Web_1_KickoffKits: tryRequire('./Property1Web_1_KickoffKits.png') || require('./questionMark.png'),
	BellSimple_Vector: tryRequire('./BellSimple_Vector.png') || require('./questionMark.png'),
	nouncloset36900131_Vector: tryRequire('./nouncloset36900131_Vector.png') || require('./questionMark.png'),
	Heart_2_Vector: tryRequire('./Heart_2_Vector.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector: tryRequire('./OrderIconTrackoutlined_Vector.png') || require('./questionMark.png'),
	User_1_Vector: tryRequire('./User_1_Vector.png') || require('./questionMark.png'),
	nouncloset36947041_Vector: tryRequire('./nouncloset36947041_Vector.png') || require('./questionMark.png'),
	OrderIconTrackFilled_Subtract: tryRequire('./OrderIconTrackFilled_Subtract.png') || require('./questionMark.png'),
	User_2_Vector: tryRequire('./User_2_Vector.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_1: tryRequire('./PaymentConfirmationModalMobileView_Vector_1.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_1: tryRequire('./PaymentConfirmationModalDesktop_Vector_1.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector_1: tryRequire('./OrderIconTrackoutlined_Vector_1.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_2: tryRequire('./PaymentConfirmationModalMobileView_Vector_2.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_2: tryRequire('./PaymentConfirmationModalDesktop_Vector_2.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector_2: tryRequire('./OrderIconTrackoutlined_Vector_2.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_3: tryRequire('./PaymentConfirmationModalMobileView_Vector_3.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_3: tryRequire('./PaymentConfirmationModalDesktop_Vector_3.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector_3: tryRequire('./OrderIconTrackoutlined_Vector_3.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_4: tryRequire('./PaymentConfirmationModalMobileView_Vector_4.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_4: tryRequire('./PaymentConfirmationModalDesktop_Vector_4.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector_4: tryRequire('./OrderIconTrackoutlined_Vector_4.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_5: tryRequire('./PaymentConfirmationModalMobileView_Vector_5.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_5: tryRequire('./PaymentConfirmationModalDesktop_Vector_5.png') || require('./questionMark.png'),
	OrderIconTrackoutlined_Vector_5: tryRequire('./OrderIconTrackoutlined_Vector_5.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_6: tryRequire('./PaymentConfirmationModalMobileView_Vector_6.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_6: tryRequire('./PaymentConfirmationModalDesktop_Vector_6.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_7: tryRequire('./PaymentConfirmationModalMobileView_Vector_7.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_7: tryRequire('./PaymentConfirmationModalDesktop_Vector_7.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_8: tryRequire('./PaymentConfirmationModalMobileView_Vector_8.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_8: tryRequire('./PaymentConfirmationModalDesktop_Vector_8.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_9: tryRequire('./PaymentConfirmationModalMobileView_Vector_9.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_9: tryRequire('./PaymentConfirmationModalDesktop_Vector_9.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_10: tryRequire('./PaymentConfirmationModalMobileView_Vector_10.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_10: tryRequire('./PaymentConfirmationModalDesktop_Vector_10.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_11: tryRequire('./PaymentConfirmationModalMobileView_Vector_11.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_11: tryRequire('./PaymentConfirmationModalDesktop_Vector_11.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_12: tryRequire('./PaymentConfirmationModalMobileView_Vector_12.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_12: tryRequire('./PaymentConfirmationModalDesktop_Vector_12.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_13: tryRequire('./PaymentConfirmationModalMobileView_Vector_13.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_13: tryRequire('./PaymentConfirmationModalDesktop_Vector_13.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_14: tryRequire('./PaymentConfirmationModalMobileView_Vector_14.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_14: tryRequire('./PaymentConfirmationModalDesktop_Vector_14.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_15: tryRequire('./PaymentConfirmationModalMobileView_Vector_15.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_15: tryRequire('./PaymentConfirmationModalDesktop_Vector_15.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_16: tryRequire('./PaymentConfirmationModalMobileView_Vector_16.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_16: tryRequire('./PaymentConfirmationModalDesktop_Vector_16.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_17: tryRequire('./PaymentConfirmationModalMobileView_Vector_17.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_17: tryRequire('./PaymentConfirmationModalDesktop_Vector_17.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_18: tryRequire('./PaymentConfirmationModalMobileView_Vector_18.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_18: tryRequire('./PaymentConfirmationModalDesktop_Vector_18.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_19: tryRequire('./PaymentConfirmationModalMobileView_Vector_19.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_19: tryRequire('./PaymentConfirmationModalDesktop_Vector_19.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_20: tryRequire('./PaymentConfirmationModalMobileView_Vector_20.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_20: tryRequire('./PaymentConfirmationModalDesktop_Vector_20.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_21: tryRequire('./PaymentConfirmationModalMobileView_Vector_21.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_21: tryRequire('./PaymentConfirmationModalDesktop_Vector_21.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_22: tryRequire('./PaymentConfirmationModalMobileView_Vector_22.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_22: tryRequire('./PaymentConfirmationModalDesktop_Vector_22.png') || require('./questionMark.png'),
	PaymentConfirmationModalMobileView_Vector_23: tryRequire('./PaymentConfirmationModalMobileView_Vector_23.png') || require('./questionMark.png'),
	PaymentConfirmationModalDesktop_Vector_23: tryRequire('./PaymentConfirmationModalDesktop_Vector_23.png') || require('./questionMark.png'),
}